-- Önce eski kolonları siliyoruz
ALTER TABLE vendors DROP COLUMN IF EXISTS name;
ALTER TABLE vendors DROP COLUMN IF EXISTS email;
ALTER TABLE vendors DROP COLUMN IF EXISTS phone;

-- Yeni kolonları ekliyoruz (eğer yoksa)
ALTER TABLE vendors 
ADD COLUMN IF NOT EXISTS store_name VARCHAR(255) NOT NULL DEFAULT 'Default Store',
ADD COLUMN IF NOT EXISTS store_description TEXT,
ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255) NOT NULL DEFAULT 'store@example.com',
ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(20) NOT NULL DEFAULT '+90000000000',
ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS review_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_orders INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true; 